const wordCluePairs = [
    { word: "APPLE", clue: `Red temptation waits\nSilent on the wooden desk\nA crunch, then a thought` },
    { word: "CHAIR", clue: `Four legs bear the weight\nIt listens to every word\nAnd never complains` },
    { word: "BRUSH", clue: `Tangled paths are cleared\nPaint flows where bristles have been\nTracks in snow or hair` },
    { word: "STORM", clue: `Sky tears at the seams\nWind speaks in broken branches\nThen silence follows` },
    { word: "PLANT", clue: `Reaching toward light\nOr listening behind glass\nIt grows either way` },
    { word: "CLOUD", clue: `A drifting whisper\nHolding more than it lets fall\nShaped by wind and time` },
    { word: "BREAD", clue: `Broken and passed on\nDaily ritual of warmth\nEarned or given free` },
    { word: "MOUSE", clue: `Skittering below\nOr pointing on a glass desk\nAlways chasing things` },
    { word: "TRAIN", clue: `Iron snake on tracks\nFollows lines we do not see\nAlways moves forward` },
    { word: "WATER", clue: `Carves stone silently\nTakes the shape of what it fills\nNever holds its form` },
    { word: "HEART", clue: `Beats within the chest\nMoves not by thought, but by truth\nBreaks and yet still mends` },
    { word: "LIGHT", clue: `Cannot be captured\nReveals but also destroys\nAlways finds the crack` },
    { word: "GRAPE", clue: `Small and full of juice\nA cluster of sweetness held\nOr crushed into wine` },
    { word: "BOOKS", clue: `Stacked in quiet rows\nHolding more than just pages\nTime folded in ink` },
    { word: "FLOOD", clue: `Unexpected rise\nBreaking banks without warning\nNothing left but mud` },
    { word: "FLUTE", clue: `Silver breath released\nDancing through a narrow reed\nSings what lips cannot` },
    { word: "SMILE", clue: `Weapon made of joy\nUsed without leaving a mark\nStrongest when it’s true` },
    { word: "SHEEP", clue: `Many follow one\nClothed in clouds and calm routine\nKept within the fence` },
    { word: "CROWN", clue: `Worn but not always\nGiven more than it is earned\nShines best on the shelf` },
    { word: "BRAIN", clue: `Web of hidden sparks\nSolves puzzles while you’re asleep\nNever feels its weight` },
    { word: "GLOVE", clue: `Fits like a second\nSkin that guards against the cold\nLeft without a print` },
    { word: "CLOCK", clue: `Counts the silent steps\nSpins in circles without rest\nLoyal to the end` },
    { word: "SWORD", clue: `Drawn in time of fear\nWords may cut, but this cuts deep\nLeft in stone or hand` },
    { word: "DREAM", clue: `Not awake, not gone\nDoor that opens from inside\nBuilt from scattered stars` },
    { word: "FLOOR", clue: `Holds all your burdens\nNever complains of the weight\nClosest thing to earth` },
    { word: "VOICE", clue: `Not seen but it moves\nStirs the air and shapes the day\nBreaks and builds with ease` },
    { word: "LEMON", clue: `Yellow, sharp, and bright\nWakes the tongue like sudden light\nBitterness made bold` },
    { word: "STARS", clue: `Too far to be reached\nYet they speak in ancient light\nNames we’ll never know` },
    { word: "BLADE", clue: `Sharper than a truth\nSplits the silent from the loud\nCleanest cut is cold` },
    { word: "MIRTH", clue: `Laughter without edge\nJoy without condition shown\nShort, sincere, and warm` }
  ];
  