const wordCluePairs = [
    { word: "banks", clue: "Where trust and silence collect interest" },
    { word: "plant", clue: "Grows roots—or secrets" },
    { word: "chair", clue: "Supports you without standing" },
    { word: "flame", clue: "Born from breath, dies with a hush" },
    { word: "clock", clue: "Keeps count but never speaks" },
    { word: "spade", clue: "Buries truth or finds it" },
    { word: "trail", clue: "Left behind, followed ahead" },
    { word: "grace", clue: "Weightless, yet never free" },
    { word: "wheat", clue: "Fed the world before it knew numbers" },
    { word: "creek", clue: "Whispers over stones, never still" },
    { word: "shelf", clue: "Holds what you reach for" },
    { word: "moons", clue: "Shadows borrowed from fire" },
    { word: "hinge", clue: "Everything turns on me" },
    { word: "storm", clue: "Skies that speak in fury" },
    { word: "draft", clue: "Unfinished thoughts or breezy threats" },
    { word: "stone", clue: "Stillness you can throw" },
    { word: "linen", clue: "Woven quiet" },
    { word: "cabin", clue: "Small wood, big peace" },
    { word: "frost", clue: "Decorates before it bites" },
    { word: "grind", clue: "Turns whole into fine with time" },
    { word: "knock", clue: "A question without a voice" },
    { word: "shade", clue: "Follows form, fears light" },
    { word: "lemon", clue: "Bright bite in yellow skin" },
    { word: "siren", clue: "Calls you where you shouldn’t go" },
    { word: "brick", clue: "One among many, alone it’s nothing" },
    { word: "flint", clue: "Stone with a spark" },
    { word: "drift", clue: "Moving without aim—or anchored thought" },
    { word: "forge", clue: "Born of heat, maker of shape" },
    { word: "hatch", clue: "Begins in breakage" },
    { word: "crane", clue: "Neck of steel or bird of grace" }
  ];
  